### ISSUE TITLE
Unable to create/update fields: Name

### ISSUE THREAD

**Issue by martyychang** [martyychang/sf-automerge#2]
When merging leads, the following error occurred.

> INVALID_FIELD_FOR_INSERT_UPDATE, Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set.: [Name]

The code made the assumption that in every query the `Name` field should be returned for merging, but this is actually a bad assumption since for leads and contacts the `Name` field is a read-only concatenation of other fields.

**Comment by danhowellnz** [comment]
Hey Marty. I want to use your project a bit. Any updates on this issue and how to fix it?

**Comment by danhowellnz** [comment]
Don't worry I found it on line 41 and I fixed your other issue. I thought both of those were easier to upload then add an issue in. Did you have more up to date code?

**Comment by martyychang** [comment]
Hi @danhowellnz thank you for the follow-up. I actually did update the code in my last implementation project but did not bring that back to this repo. I'll aim to make the update sometime this week.

**Comment by martyychang** [comment]
Hmm... I can't seem to reproduce this issue anymore in the code, but I'll go ahead and create a pr to add a unit test proving that the issue is a non-issue, and I'll also remove what I confirmed was the fix I deployed on my other project.

**Comment by martyychang** [comment]
Merged #7

**Comment by martyychang** [comment]
Actually in trying to resolve #1 I realized the problem was in using `getQuery` in conjunction with one of the merge methods, because `getQuery` would have returned the unwritable `Name` field
